AspNetSecurity/Controllers/ConferenceController.cs
using AspNetSecurity.Models;
using AspNetSecurity.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetSecurity.Controllers
{
    [Authorize]
    public class ConferenceController : Controller
    {
        private readonly ConferenceRepo _repo;

        public ConferenceController(ConferenceRepo repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Organizer - Conference Overview";
            return View(_repo.GetAll());
        }

        public IActionResult Add()
        {
            ViewBag.Title = "Organizer - Add Conference";
            return View(new ConferenceModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(ConferenceModel model)
        {
            if (ModelState.IsValid)
                _repo.Add(model);

            return RedirectToAction("Index");
        }
    }
}

AspNetSecurity/Controllers/ProposalController.cs
using AspNetSecurity.Models;
using AspNetSecurity.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;

namespace AspNetSecurity.Controllers
{
    [Authorize]
    public class ProposalController : Controller
    {
        private readonly ConferenceRepo _conferenceRepo;
        private readonly ProposalRepo _proposalRepo;
        private readonly IDataProtector _protector;

        public ProposalController(ConferenceRepo conferenceRepo, ProposalRepo proposalRepo,
            IDataProtectionProvider dataProtectionProvider, PurposeStringConstants constants)
        {
            _protector = dataProtectionProvider.CreateProtector(constants.ConferenceIdQueryString);

            _conferenceRepo = conferenceRepo;
            _proposalRepo = proposalRepo;
        }

        public IActionResult Index(string conferenceId)
        {
            var deCryptedConferenceId = int.Parse(_protector.Unprotect(conferenceId));
            var conference = _conferenceRepo.GetById(deCryptedConferenceId);
            ViewBag.Title = $"Speaker - Proposals For Conference {conference.Name} {conference.Location}";
            ViewBag.ConferenceId = conferenceId;

            return View(_proposalRepo.GetAllForConference(deCryptedConferenceId));
        }

        public IActionResult AddProposal(int conferenceId)
        {
            ViewBag.Title = "Speaker - Add Proposal";
            return View(new ProposalModel {ConferenceId = conferenceId});
        }

        [HttpPost]
        public IActionResult AddProposal(ProposalModel proposal)
        {
            if (ModelState.IsValid)
                _proposalRepo.Add(proposal);
            return RedirectToAction("Index", new {conferenceId = proposal.ConferenceId});
        }

        public IActionResult Approve(int proposalId)
        {
            var proposal = _proposalRepo.Approve(proposalId);
            return RedirectToAction("Index", new {conferenceId = proposal.ConferenceId});
        }
    }
}

AspNetSecurity/Views/Conference/Add.cshtml
@model AspNetSecurity.Models.ConferenceModel

<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Name" autocomplete="off" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Location"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" asp-for="Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 col-md-offset-2">
            <label asp-for="Start"></label>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="date" asp-for="Start" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

AspNetSecurity/Views/Conference/Index.cshtml
@using AspNetSecurity.Models
@using AspNetSecurity.Repositories
@model IEnumerable<ConferenceModel>
@inject AttendeeRepo AttendeeRepo
<div class="row">
    <div class="col-md-10 col-md-offset-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Start of event</th>
                <th>Attendees</th>
                <th>Actions</th>
            </tr>
            @foreach (var conference in Model)
            {
                <tr>
                    <td>@Html.Raw(@conference.Name)</td>
                    <td>@conference.Location</td>
                    <td>@conference.Start.ToString("ddd d MMM")</td>
                    <td>@AttendeeRepo.GetAttendeesTotal(conference.Id)</td>
                    <td>
                        <a asp-controller="Proposal" asp-action="Index" asp-route-conferenceId="@conference.EncryptedId">Proposals</a>
                    </td>
                </tr>
            }
        </table>
        <a asp-action="Add">Add</a>

    </div>
</div>

@foreach (var claim in User.Claims)
{
    <dt>@claim.Type</dt>
    <dd>@claim.Value</dd>

}